name: Deployment
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/deploy.yaml'
      - 'terraform/**'
      - 'compose/**'
      - 'config.yaml'
jobs:
  deploy-instance:
    name: Deploy EC2 Instance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Python Setup
        uses: actions/setup-python@v2

      - name: Install Python Packages
        run: |
          pip install ec2-manager

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Update Instance
        run: |
          export COMMIT=${{ github.sha }}
          export REPO=${{ github.event.repository.name }}
          export GITHUB_USERNAME=$GITHUB_REPOSITORY_OWNER
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          export AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }}
          export ENV_FILE=${{ secrets.ENV_FILE }}
          ec2-manager apply