[tool.poetry]
name = "api66jenkins"
version = "0.0.6"
description = "Python3 client library for Jenkins API. Adding a keyword from api4jenkins  add job.build [custom] parameter"
authors = ["sanmejie <liyapong@foxmail.com>"]
readme = "README.md"
license = "LICENSE"


[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.28.1"
api4jenkins = "^1.12"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# [tool.poetry.scripts]
# # # 前面是命令 开头 , = 后面是 指定typer实例, 对应的就是 打包包名.模块名(main.py文件).typer对象名
# tdo = 'api66jenkins'
