[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "yeectl"
version = "0.0.1"
authors = [
	{ name="Bean Robinson", email="beanrobinson@duck.com" },
]
description="Python TUI for controlling Yeelights"
readme="README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [ 
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"GitHub" = "https://github.com/Bean499/yeectl"
