[tool.poetry]
name = "jdv_funcutils"
version = "1.0.2"
description = "Function utilties."
authors = ["Justin Vrana <justin.vrana@justbiotherapeutics.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Sphinx = {version = "^5.0.1", optional = true}
sphinx-rtd-theme = {version = "^1.0.0", optional = true}
sphinx-autodoc-typehints = {version = "^1.18.2", optional = true}
PyYAML = {version = "^6.0", optional = true}
typing-extensions = "^4.3.0"


[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pre-commit = "^2.19.0"
tox = "^3.25.0"
pylint = "^2.15.2"

[tool.poetry.extras]
documentation = ["Sphinx", "sphinx-rtd-theme", "sphinx-autodoc-typehints", "sphinxcontrib-confluencebuilder", "PyYAML"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
include = ["jdv_funcutils"]
exclude = ["**/node_modules",
    "**/__pycache__",
    "tests"
]
typeCheckingMode = "strict"