[project]
description = "A pytest plugin that imports CPPython testing types"
name = "pytest-cppython"
license-expression = "MIT"
authors = [
    { name = "Synodic Software", email = "contact@synodic.software" },
]
readme = "README.md"
dynamic = []
requires-python = ">=3.10"
dependencies = [
    "cppython-core>=0.4.1.dev13",
    "pydantic>=1.9.2",
]
version = "0.2.1.dev9"

[project.license-files]
paths = [
    "LICENSE.md",
]

[project.urls]
homepage = "https://github.com/Synodic-Software/Pytest-CPPython"
repository = "https://github.com/Synodic-Software/Pytest-CPPython"

[tool.pdm.version]
use_scm = true

[tool.pdm.dev-dependencies]
lint = [
    "black>=22.6.0",
    "pylint>=2.14.4",
    "isort>=5.10.1",
]
test = [
    "pytest >=7.1.2",
    "pytest-cov>=3.0.0",
    "pytest-mock>=3.8.2",
]

[tool.entry-points.pytest11]
pytest_cppython = "pytest_cppython.plugin"

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
testpaths = [
    "tests",
]

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.pylint.messages_control]
extension-pkg-whitelist = "pydantic"

[tool.pylint.format]
max-line-length = "120"

[build-system]
build-backend = "pdm.pep517.api"
requires = [
    "pdm-pep517",
]
