[tool.poetry]
name = "vdd"
version = "0.4.0"
description = "Tools for Value-Driven Design"
authors = ["Alex Corrie <ajccode@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7.1"
platformdirs = "^2.5.2"
pygsheets = "^2.0.5"
pandas = "*"
numpy = "*"
xlrd = "^2.0"
pytz = "^2022.2.1"
openpyxl = "^3.0.10"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.2"
pytest-mock = "^3.8.2"
coverage = {extras = ["toml"], version = "^6.4.4"}
ddt = "^1.6.0"
pytest-cov = "^3.0.0"

[tool.poetry.group.azp]
optional = true

[tool.poetry.group.azp.dependencies]
pytest-azurepipelines = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
